# Section 1 - API Version
apiVersion: v1
# Section 2 - Which type of Object we want to create
kind: Pod
# Section 3 - Meta data of the object we are creating
metadata:
  name: sample-pod
  labels:
    app: sample
    env: dev
# Section 4 - The actual options we need for the object we want to create
spec:
  containers:
  - name: sample-container
    image: nginx:latest
    resources:
      limits:
        memory: 500M
