// Code generated by informer-gen. DO NOT EDIT.

package v1alpha1

import (
	"context"
	time "time"

	configurationv1alpha1 "github.com/nginxinc/kubernetes-ingress/pkg/apis/configuration/v1alpha1"
	versioned "github.com/nginxinc/kubernetes-ingress/pkg/client/clientset/versioned"
	internalinterfaces "github.com/nginxinc/kubernetes-ingress/pkg/client/informers/externalversions/internalinterfaces"
	v1alpha1 "github.com/nginxinc/kubernetes-ingress/pkg/client/listers/configuration/v1alpha1"
	v1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
	watch "k8s.io/apimachinery/pkg/watch"
	cache "k8s.io/client-go/tools/cache"
)

// GlobalConfigurationInformer provides access to a shared informer and lister for
// GlobalConfigurations.
type GlobalConfigurationInformer interface {
	Informer() cache.SharedIndexInformer
	Lister() v1alpha1.GlobalConfigurationLister
}

type globalConfigurationInformer struct {
	factory          internalinterfaces.SharedInformerFactory
	tweakListOptions internalinterfaces.TweakListOptionsFunc
	namespace        string
}

// NewGlobalConfigurationInformer constructs a new informer for GlobalConfiguration type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewGlobalConfigurationInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers) cache.SharedIndexInformer {
	return NewFilteredGlobalConfigurationInformer(client, namespace, resyncPeriod, indexers, nil)
}

// NewFilteredGlobalConfigurationInformer constructs a new informer for GlobalConfiguration type.
// Always prefer using an informer factory to get a shared informer instead of getting an independent
// one. This reduces memory footprint and number of connections to the server.
func NewFilteredGlobalConfigurationInformer(client versioned.Interface, namespace string, resyncPeriod time.Duration, indexers cache.Indexers, tweakListOptions internalinterfaces.TweakListOptionsFunc) cache.SharedIndexInformer {
	return cache.NewSharedIndexInformer(
		&cache.ListWatch{
			ListFunc: func(options v1.ListOptions) (runtime.Object, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.K8sV1alpha1().GlobalConfigurations(namespace).List(context.TODO(), options)
			},
			WatchFunc: func(options v1.ListOptions) (watch.Interface, error) {
				if tweakListOptions != nil {
					tweakListOptions(&options)
				}
				return client.K8sV1alpha1().GlobalConfigurations(namespace).Watch(context.TODO(), options)
			},
		},
		&configurationv1alpha1.GlobalConfiguration{},
		resyncPeriod,
		indexers,
	)
}

func (f *globalConfigurationInformer) defaultInformer(client versioned.Interface, resyncPeriod time.Duration) cache.SharedIndexInformer {
	return NewFilteredGlobalConfigurationInformer(client, f.namespace, resyncPeriod, cache.Indexers{cache.NamespaceIndex: cache.MetaNamespaceIndexFunc}, f.tweakListOptions)
}

func (f *globalConfigurationInformer) Informer() cache.SharedIndexInformer {
	return f.factory.InformerFor(&configurationv1alpha1.GlobalConfiguration{}, f.defaultInformer)
}

func (f *globalConfigurationInformer) Lister() v1alpha1.GlobalConfigurationLister {
	return v1alpha1.NewGlobalConfigurationLister(f.Informer().GetIndexer())
}
