apiVersion: batch/v1
kind: CronJob
metadata:
  name: countdown
spec:
  schedule: "*/10 * * * *"
  jobTemplate:
    spec:
      template:
        spec:               
          containers:
          - name: counter
            image: centos:7
            command:
             - "bin/bash"
             - "-c"
             - "for i in 9 8 7 6 5 4 3 2 1 ; do echo $i ; done"
          restartPolicy: Never
