// Code generated by lister-gen. DO NOT EDIT.

package v1alpha1

// GlobalConfigurationListerExpansion allows custom methods to be added to
// GlobalConfigurationLister.
type GlobalConfigurationListerExpansion interface{}

// GlobalConfigurationNamespaceListerExpansion allows custom methods to be added to
// GlobalConfigurationNamespaceLister.
type GlobalConfigurationNamespaceListerExpansion interface{}

// TransportServerListerExpansion allows custom methods to be added to
// TransportServerLister.
type TransportServerListerExpansion interface{}

// TransportServerNamespaceListerExpansion allows custom methods to be added to
// TransportServerNamespaceLister.
type TransportServerNamespaceListerExpansion interface{}
